CREATE TABLE Address(
	AddressID INT NOT NULL AUTO_INCREMENT,
    City VARCHAR(50) NOT NULL,
    Coyntry VARCHAR(50) NOT NULL,
    Province VARCHAR(50) NOT NULL,
    
    PRIMARY KEY(AddressID)
    
) ENGINE = InnoDB;
