CREATE TABLE Credentials(
	CredID INT NOT NULL AUTO_INCREMENT,
    AMKA BIGINT NOT NULL,
    Password VARCHAR(12) NOT NULL,
    
    PRIMARY KEY(CredID),
    FOREIGN KEY(AMKA) REFERENCES Employees(AMKA)
)	ENGINE = InnoDB;
